# Frontend Dockerfile

# Base image - Node.js 20
FROM node:20-slim AS build

# Set working directory
WORKDIR /app

# Copy the package.json file
COPY package.json .

# Install deps
RUN npm install

# Copy the rest of the application code
COPY . . 

# Build the application
RUN npm run build


# Serving static files from the out/ directory using Nginx
FROM nginx:stable-alpine

# Copy the output to the working dir
COPY --from=build /app/out/ /usr/share/nginx/html/

# Expose port
EXPOSE 80


# Start Nginx
CMD ["nginx", "-g", "daemon off;"]




